/* 05_실습_SQL04_DDL.pdf */
/* 1번 문제 */
CREATE TABLE TB_CATEGORY(
NAME VARCHAR2(10)
 , USE_YN CHAR(1) DEFAULT('Y') CONSTRAINT TB_CATEGORY_USE_YN_CK CHECK(USE_YN IN('Y', 'N'))
);
/* 2번 문제 */
CREATE TABLE TB_CLASS_TYPE(
NO VARCHAR2(5) CONSTRAINT TB_CLASS_TYPE_NO_PK PRIMARY KEY
 , NAME VARCHAR2(10)
);
/* 3번 문제 */
ALTER TABLE TB_CATEGORY ADD CONSTRAINT TB_CATEGORY_NAME_PK PRIMARY KEY(NAME);
/* 4번 문제 */
ALTER TABLE TB_CLASS_TYPE MODIFY NAME CONSTRAINT TB_CLASS_TYPE_NAME_NN NOT NULL;
/* 5번 문제 */
ALTER TABLE TB_CATEGORY MODIFY NAME VARCHAR2(20);
ALTER TABLE TB_CLASS_TYPE MODIFY NO VARCHAR2(10);
ALTER TABLE TB_CLASS_TYPE MODIFY NAME VARCHAR2(20);
/* 6번 문제 */
ALTER TABLE TB_CATEGORY RENAME COLUMN NAME TO CATEGORY_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NO TO CLASS_TYPE_NO;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NAME TO CLASS_TYPE_NAME;
/* 7번 문제 */
ALTER TABLE TB_CATEGORY RENAME CONSTRAINT TB_CATEGORY_NAME_PK TO PK_CATEGORY_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME CONSTRAINT TB_CLASS_TYPE_NO_PK TO PK_CLASS_TYPE_NO;
/* 8번 문제 */
INSERT INTO TB_CATEGORY VALUES('공학', 'Y');
INSERT INTO TB_CATEGORY VALUES('자연과학', 'Y');
INSERT INTO TB_CATEGORY VALUES('의학', 'Y');
INSERT INTO TB_CATEGORY VALUES('예쳬능', 'Y');
INSERT INTO TB_CATEGORY VALUES('인문사회', 'Y');
/* 9번 문제 */
ALTER TABLE TB_DEPARTMENT ADD CONSTRAINT FK_DEPARTMENT_CATEGORY FOREIGN KEY(CATEGORY) 
 REFERENCES TB_CATEGORY(CATEGORY_NAME);
/* 10번 문제 */
CREATE OR REPLACE VIEW VW_학생일반정보
AS 
SELECT STUDENT_NO AS 학번
 , STUDENT_NAME AS 학생이름
 , STUDENT_ADDRESS AS 주소
 FROM TB_STUDENT;
/* 11번 문제 */
CREATE OR REPLACE VIEW VW_지도면담
AS
SELECT STUDENT_NAME AS 학생이름
 , (SELECT DEPARTMENT_NAME 
 FROM TB_DEPARTMENT D
 WHERE D.DEPARTMENT_NO = S.DEPARTMENT_NO) AS 학과이름
 , NVL((SELECT PROFESSOR_NAME
 FROM TB_PROFESSOR P
 WHERE P.PROFESSOR_NO = S.COACH_PROFESSOR_NO), '지도교수없음') AS 지도교수이름
 FROM TB_STUDENT S
 ORDER BY 2
 WITH READ ONLY;
 /* 12번 문제 */
 CREATE OR REPLACE VIEW VW_학과별학생수
 AS
 SELECT D.DEPARTMENT_NAME
 , COUNT(*) AS STUDENT_COUNT
 FROM TB_DEPARTMENT D
 JOIN TB_STUDENT S 
 ON D.DEPARTMENT_NO = S.DEPARTMENT_NO
 GROUP BY D.DEPARTMENT_NAME;
/* 13번 문제 */
UPDATE VW_학생일반정보
 SET 학생이름 = '김태룡'
 WHERE 학번 = 'A213046';
/* 14번 문제 */
/*
 WITH READ ONLY로 작성하면 된다.
 CREATE OR REPLACE VIEW VW_학생일반정보
 AS 
 SELECT STUDENT_NO AS 학번
 , STUDENT_NAME AS 학생이름
 , STUDENT_ADDRESS AS 주소
 FROM TB_STUDENT
 WITH READ ONLY;
 */
/* 15번 문제 */
SELECT 순위
 , 과목번호
 , 과목이름
 , 누적수강생수
 FROM (SELECT RANK() OVER(ORDER BY COUNT(*) DESC) AS 순위
 , G.CLASS_NO AS 과목번호
 , C.CLASS_NAME AS 과목이름
 , COUNT(*) AS 누적수강생수
 FROM TB_GRADE G
 JOIN TB_CLASS C
 ON G.CLASS_NO = C.CLASS_NO
 WHERE SUBSTR(TERM_NO, 1, 4) IN('2007', '2008', '2009')
 GROUP BY G.CLASS_NO, C.CLASS_NAME)
 WHERE 순위 <= 3;
