/* 05_실습_SQL01_SELECT(Basic).pdf */
/* 1번 문제 */ 
SELECT DEPARTMENT_NAME AS "학과 명"
 , CATEGORY AS 계열
 FROM TB_DEPARTMENT
 ORDER BY DEPARTMENT_NO;
 
/* 2번 문제 */
SELECT DEPARTMENT_NAME || '의 정원은 ' || CAPACITY || '명 입니다.' AS "학과별 정원"
 FROM TB_DEPARTMENT
 ORDER BY DEPARTMENT_NO;
 
/* 3번 문제 */
SELECT STUDENT_NAME
 FROM TB_STUDENT
 WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO
 FROM TB_DEPARTMENT
 WHERE DEPARTMENT_NAME = '국어국문학과')
 AND SUBSTR(STUDENT_SSN, 8, 1) = '2'
 AND ABSENCE_YN = 'Y';
 
/* 4번 문제 */
SELECT STUDENT_NAME
 FROM TB_STUDENT
 WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119')
 ORDER BY STUDENT_NO DESC;
/* 5번 문제 */
SELECT DEPARTMENT_NAME
 , CATEGORY
 FROM TB_DEPARTMENT
 WHERE CAPACITY BETWEEN 20 AND 30
 ORDER BY DEPARTMENT_NO;
/* 6번 문제 */
SELECT PROFESSOR_NAME
 FROM TB_PROFESSOR
 WHERE DEPARTMENT_NO IS NULL;
/* 7번 문제 */
SELECT * FROM TB_STUDENT WHERE DEPARTMENT_NO IS NULL;
/* 8번 문제 */
SELECT CLASS_NO
 FROM TB_CLASS
 WHERE PREATTENDING_CLASS_NO IS NOT NULL;
/* 9번 문제 */
SELECT CATEGORY
 FROM TB_DEPARTMENT
 GROUP BY CATEGORY
 ORDER BY CATEGORY;
/* 10번 문제 */
SELECT STUDENT_NO
 , STUDENT_NAME
 , STUDENT_SSN
 FROM (SELECT * 
 FROM TB_STUDENT
 WHERE SUBSTR(STUDENT_NO,2,1) = 2
 AND STUDENT_ADDRESS LIKE '%전주%'
 AND ABSENCE_YN = 'N');