/* 05_실습_SQL05_DML.pdf */
/* 1번 문제 */
INSERT INTO TB_CLASS_TYPE VALUES('01', '전공필수');
INSERT INTO TB_CLASS_TYPE VALUES('02', '전공선택');
INSERT INTO TB_CLASS_TYPE VALUES('03', '교양필수');
INSERT INTO TB_CLASS_TYPE VALUES('04', '교양선택');
INSERT INTO TB_CLASS_TYPE VALUES('05', '논문지도');
/* 2번 문제 */
CREATE TABLE TB_학생일반정보
AS
SELECT STUDENT_NO AS 학번
 , STUDENT_NAME AS 학생이름
 , STUDENT_ADDRESS AS 주소
 FROM TB_STUDENT;
/* 3번 문제 */
CREATE TABLE TB_국어국문학과
AS
SELECT S.STUDENT_NO AS 학번
 , S.STUDENT_NAME AS 학생이름
 , TO_CHAR(1900 + SUBSTR(S.STUDENT_SSN, 1, 2)) AS 출생년도
 , P.PROFESSOR_NAME AS 교수이름
 , D1.DEPARTMENT_NAME
 FROM TB_STUDENT S
 JOIN TB_PROFESSOR P 
 ON S.COACH_PROFESSOR_NO = P.PROFESSOR_NO
 JOIN TB_DEPARTMENT D1 
 ON S.DEPARTMENT_NO = D1.DEPARTMENT_NO 
 WHERE S.DEPARTMENT_NO = (SELECT D2.DEPARTMENT_NO 
 FROM TB_DEPARTMENT D2
 WHERE D2.DEPARTMENT_NAME = '국어국문학과');
 
 /* 4번 문제 */ 
 UPDATE TB_DEPARTMENT 
 SET CAPACITY = ROUND(CAPACITY * 1.1);
 /* 5번 문제 */
 UPDATE TB_STUDENT
 SET STUDENT_ADDRESS = '서울시 종로구 숭인동 181-21'
 WHERE STUDENT_NO = 'A413042';
 /* 6번 문제 */
 UPDATE TB_STUDENT
 SET STUDENT_SSN = SUBSTR(STUDENT_SSN, 1, 6);
 /* 7번 문제 */
 UPDATE TB_GRADE
 SET POINT = 3.5
 WHERE STUDENT_NO = (SELECT STUDENT_NO
 FROM TB_STUDENT
 WHERE STUDENT_NAME = '김명훈'
 AND DEPARTMENT_NO = (SELECT DEPARTMENT_NO
 FROM TB_DEPARTMENT
 WHERE DEPARTMENT_NAME = '의학과'))
 AND TERM_NO = '200501'
 AND CLASS_NO = (SELECT CLASS_NO
 FROM TB_CLASS
 WHERE CLASS_NAME = '피부생리학');
 /* 8번 문제 */ 
 DELETE 
 FROM TB_GRADE
 WHERE STUDENT_NO IN (SELECT STUDENT_NO
 FROM TB_STUDENT
 WHERE ABSENCE_YN = 'Y');