/* 05_실습_SQL03_SELECT(Option).pdf */
/* 1번 문제 */ 
SELECT STUDENT_NAME AS "학생 이름"
 , STUDENT_ADDRESS AS 주소지
 FROM TB_STUDENT
 ORDER BY 1;
/* 2번 문제 */
SELECT STUDENT_NAME
 , STUDENT_SSN
 FROM TB_STUDENT
 WHERE ABSENCE_YN = 'Y'
 ORDER BY 2 DESC;
/* 3번 문제 */
SELECT STUDENT_NAME AS 학생이름
 , STUDENT_NO AS 학번
 , STUDENT_ADDRESS AS "거주지 주소"
 FROM TB_STUDENT
 WHERE STUDENT_NO NOT LIKE '%A%'
 AND (STUDENT_ADDRESS LIKE '%강원도%' OR STUDENT_ADDRESS LIKE '%경기도%')
 ORDER BY 1; 
/* 4번 문제 */
SELECT PROFESSOR_NAME
 , PROFESSOR_SSN
 FROM TB_PROFESSOR
 WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO 
 FROM TB_DEPARTMENT
 WHERE DEPARTMENT_NAME = '법학과')
 ORDER BY 2;
/* 5번 문제 */
SELECT STUDENT_NO
 , TO_CHAR(POINT, '9.00') AS POINT
 FROM TB_GRADE
 WHERE TERM_NO LIKE '%200402%'
 AND CLASS_NO = 'C3118100'
 ORDER BY 2 DESC, 1;
/* 6번 문제 */
SELECT S.STUDENT_NO
 , S.STUDENT_NAME
 , D.DEPARTMENT_NAME
 FROM TB_STUDENT S
 JOIN TB_DEPARTMENT D 
 ON S.DEPARTMENT_NO = D.DEPARTMENT_NO 
 ORDER BY S.STUDENT_NAME DESC;
/* 7번 문제 */ 
SELECT C.CLASS_NAME
 , D.DEPARTMENT_NAME
 FROM TB_CLASS C
 JOIN TB_DEPARTMENT D
 USING (DEPARTMENT_NO)
 ORDER BY 2, 1;
 
/* 8번 문제 */
SELECT C.CLASS_NAME
 , P.PROFESSOR_NAME
 FROM TB_CLASS C
 JOIN TB_PROFESSOR P
 ON C.DEPARTMENT_NO = P.DEPARTMENT_NO
 ORDER BY 2, 1;
/* 9번 문제 */
SELECT C.CLASS_NAME
 , P.PROFESSOR_NAME
 FROM TB_CLASS C
 JOIN TB_PROFESSOR P
 ON C.DEPARTMENT_NO = P.DEPARTMENT_NO
 JOIN TB_DEPARTMENT D
ON C.DEPARTMENT_NO = D.DEPARTMENT_NO
 WHERE D.CATEGORY = '인문사회'
 ORDER BY 2, 1;
/* 10번 문제 */
SELECT S.STUDENT_NO AS 학번
 , S.STUDENT_NAME AS "학생 이름"
 , ROUND(AVG(G.POINT),1) AS "전체 평점"
 FROM TB_STUDENT S
 JOIN TB_GRADE G 
 ON S.STUDENT_NO = G.STUDENT_NO
 JOIN TB_DEPARTMENT D 
 ON S.DEPARTMENT_NO = D.DEPARTMENT_NO
 WHERE D.DEPARTMENT_NAME = '음악학과'
 GROUP BY S.STUDENT_NO, STUDENT_NAME
 ORDER BY 1;
/* 11번 문제 */
SELECT D.DEPARTMENT_NAME AS 학과이름
 , S.STUDENT_NAME AS 학생이름
 , P.PROFESSOR_NAME AS 지도교수이름
 FROM TB_STUDENT S 
 JOIN TB_PROFESSOR P
 ON S.COACH_PROFESSOR_NO = P.PROFESSOR_NO 
 JOIN TB_DEPARTMENT D
 ON S.DEPARTMENT_NO = D.DEPARTMENT_NO 
 WHERE STUDENT_NO = 'A313047';
/* 12번 문제 */
SELECT S.STUDENT_NAME
 , G.TERM_NO AS TERM_NAME
 FROM TB_STUDENT S
 JOIN TB_GRADE G
 ON S.STUDENT_NO = G.STUDENT_NO 
 JOIN TB_CLASS C
 ON S.DEPARTMENT_NO = C.DEPARTMENT_NO
 WHERE G.TERM_NO LIKE '2007%'
 AND C.CLASS_NAME = '인간관계론'
 ORDER BY 2, 1;
/* 13번 문제 */
SELECT CLASS_NAME
 , DEPARTMENT_NAME
 FROM TB_DEPARTMENT D
 JOIN TB_CLASS C
 ON C.DEPARTMENT_NO = D.DEPARTMENT_NO 
 FULL OUTER JOIN TB_CLASS_PROFESSOR CP 
 ON C.CLASS_NO = CP.CLASS_NO
 WHERE D.CATEGORY = '예체능'
 AND CP.PROFESSOR_NO IS NULL
 ORDER BY 2, 1;
 
 /* 14번 문제 */
 SELECT S.STUDENT_NAME AS 학생이름
 , NVL(P.PROFESSOR_NAME, '지도교수 미지정') AS 지도교수 
 , D.DEPARTMENT_NAME
 FROM TB_STUDENT S
 FULL OUTER JOIN TB_PROFESSOR P
 ON S.COACH_PROFESSOR_NO = P.PROFESSOR_NO 
 JOIN TB_DEPARTMENT D
 ON S.DEPARTMENT_NO = D.DEPARTMENT_NO 
 WHERE D.DEPARTMENT_NAME = '서반아어학과'
 ORDER BY STUDENT_NO ;
/* 15번 문제 */
SELECT S.STUDENT_NO
 , S.STUDENT_NAME
 , D.DEPARTMENT_NAME
 , AVG(G.POINT)
 FROM TB_STUDENT S
 JOIN TB_DEPARTMENT D
 ON S.DEPARTMENT_NO = D.DEPARTMENT_NO 
 JOIN TB_GRADE G 
 ON S.STUDENT_NO = G.STUDENT_NO
 WHERE S.ABSENCE_YN = 'N'
 GROUP BY S.STUDENT_NO
 , S.STUDENT_NAME
 , D.DEPARTMENT_NAME
 HAVING AVG(G.POINT) >= 4.0
 ORDER BY 1;
/* 16번 문제 */
SELECT C.CLASS_NO
 , C.CLASS_NAME
 , AVG(G.POINT)
 FROM TB_CLASS C
 JOIN TB_GRADE G 
 ON C.CLASS_NO = G.CLASS_NO
 JOIN TB_DEPARTMENT D
ON C.DEPARTMENT_NO = D.DEPARTMENT_NO
 WHERE D.DEPARTMENT_NAME = '환경조경학과'
 AND C.CLASS_TYPE LIKE '%전공%'
 GROUP BY C.CLASS_NO
 , C.CLASS_NAME
 ORDER BY 1;
/* 17번 문제 */
SELECT STUDENT_NAME
 , STUDENT_ADDRESS 
 FROM TB_STUDENT
 WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO
 FROM TB_STUDENT
 WHERE STUDENT_NAME = '최경희'
 AND STUDENT_NO = 'A513110')
 ORDER BY 1 DESC;
/* 18번 문제 */
SELECT S.STUDENT_NO
 , S.STUDENT_NAME
 FROM TB_STUDENT S
 JOIN TB_GRADE G
 ON S.STUDENT_NO = G.STUDENT_NO 
 JOIN TB_DEPARTMENT D 
 ON S.DEPARTMENT_NO = D.DEPARTMENT_NO 
 WHERE D.DEPARTMENT_NAME = '국어국문학과'
 GROUP BY ROWNUM
 , S.STUDENT_NO
 , S.STUDENT_NAME
 HAVING ROWNUM = 1;
/* 19번 문제 */
SELECT DEPARTMENT_NAME AS "계열 학과명"
 , ROUND(AVG(POINT),1) AS 전공평점
 FROM TB_DEPARTMENT D
 JOIN TB_CLASS C 
 ON D.DEPARTMENT_NO = C.DEPARTMENT_NO
 JOIN TB_GRADE G 
 ON C.CLASS_NO = G.CLASS_NO
 WHERE D.CATEGORY = (SELECT CATEGORY
 FROM TB_DEPARTMENT
 WHERE DEPARTMENT_NAME = '환경조경학과')
 AND C.CLASS_TYPE LIKE '%전공%'
 GROUP BY DEPARTMENT_NAME
 ORDER BY 1;