/* 
 * 인덱스 재구성 
 * 		- DELETE 작업으로 데이터가 제거된 경우 INDEX 색인 데이터는
 * 		  제거가 되어 있지 않기 때문에 이를 완전히 제거하고 다시 
 *        INDEX 색인을 생성하기 위해 사용.
 */
-- ALTER INDEX 인덱스명 REBUILD;

/* 인덱스 설정 확인 */
-- SELECT * FROM USER_IND_COLUMNS WHERE INDEX_NAME = '인덱스명';
-- SELECT * FROM USER_IND_COLUMNS WHERE TABLE_NAME = '테이블명';

SELECT * FROM USER_IND_COLUMNS WHERE TABLE_NAME = 'EMPLOYEES';
-- PRIMARY KEY, UNIQUE 는 INDEX 자동 설정
-- EMP_NAME_IX 는 결합인덱스

/* 인덱스를 설정하고 실행 계획을 통해 INDEX 를 사용하는지 체크 */
SELECT * FROM USER_IND_COLUMNS WHERE TABLE_NAME = 'DEPARTMENTS';

CREATE INDEX DEPT_DEPT_NAME_IX ON DEPARTMENTS(DEPARTMENT_NAME);
SELECT * FROM USER_IND_COLUMNS WHERE TABLE_NAME = 'DEPARTMENTS';

SELECT * FROM DEPARTMENTS WHERE MANAGER_ID = 200;
-- 실행계획 확인해보면 FULL ACCESS임 따라서, INDEX 설정하면 조회속도 향상에 도움을 줌.

SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'IT';
-- 실행계획(Execution plan) 확인해보면 INDEX 설정 전 후 Operation이 다름
SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID = 60;
SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_NAME > '0';